from . import checkout
from . import books
from . import authors
from . import publishers
from . import genres
from . import res_config_settings
from . import book_line
from . import res_partner
from . import account_move
from . import form_attachment
